project:
  type: website

execute:
  freeze: auto

website:
  title: The CRAN Cookbook
  site-url: https://contributor.r-project.org/cran-cookbook
  repo-url: https://github.com/r-devel/cran-cookbook
  repo-actions: [edit, source, issue]
  favicon: favicon.png

  page-footer:
    center: "The CRAN Cookbook (2024)"

  sidebar:
    title: "The CRAN Cookbook"
    logo: "CRAN Cookbook Hex Sticker.png"
    style: "docked"
    background: light
    search: true
    pinned: true
    align: center
    contents:
      - index.qmd
      - preface.qmd
      - general_issues.qmd
      - docs_issues.qmd
      - code_issues.qmd
      - description_issues.qmd
      - resources.qmd
    tools:
      - icon: bug-fill
        text: Report a Bug
        href:  https://github.com/r-devel/cran-cookbook/issues
      - icon: file-plus-fill
        text: Contribute a Community Recipe
        href:  https://github.com/r-devel/cran-cookbook/discussions/categories/community-contributions

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: style.css
    toc: true




