---
title: "DESCRIPTION file Issues"
format: 
  html:
    css: style.css
---

# Formatting Software Names

## Problem

The automatic spell check has flagged a software name as incorrect and results in a NOTE.

## Solution

All references to names of software, packages and API names in the description section of the DESCRIPTION file should be wrapped in single quotes. e.g.: 'ggplot2', 'Python', etc.

### Details

Words in single quotes are not flagged by the automatic spell check and may be used when appropriate to include references to software names **only**.

The description section in the [DESCRIPTION file](https://github.com/tidyverse/readr/blob/main/DESCRIPTION) of the 'readr' package provides an example which uses single quotes around the package name and file extensions:

```         
Description: The goal of 'readr' is to provide a fast and friendly way to
    read rectangular data (like 'csv', 'tsv', and 'fwf').  It is designed
    to flexibly parse many types of data found in the wild, while still
    cleanly failing when data unexpectedly changes.
```

------------------------------------------------------------------------

# Explaining Acronyms

## Problem

You are using acronyms in your DESCRIPTION file or they are flagged by the automatic spell check.

## Solution

Document all non-obvious acronyms in the [cran-comments.md](https://usethis.r-lib.org/reference/use_cran_comments.html) file to facilitate the CRAN team review.

### Details

Most acronyms that are not widely known should be explained. For example, you don’t have to explain *OLS*, *SEO*, or *DNA* but explanations should be provided for: *MEFM* or *OCCDS*. If you are unsure of the acronyms common knowledge, please document all acronyms in the package.

------------------------------------------------------------------------

# Title Case

## Problem

The package Title field in the DESCRIPTION file is not in Title Case and the first letter of some or all of the words in the title are lowercase.

## Solution

The package Title field in the DESCRIPTION file must be in Title Case, except words like "a", "the" or "of".

### Details

Determining Title Case automatically can be challenging due to word significance being only known by the package author. The function `toTitleCase()` can assist with transforming sentences into Title Case from the 'tools' package.

```{r}
tools::toTitleCase("web application framework for R")
```

::: callout-note
There are some exceptions to using Title Case for quoting longer works like book titles and shorter works like [research papers](https://www.scribbr.com/academic-writing/title-case/#:~:text=In%20title%20case%2C%20the%20first,title%2C%20subtitle%2C%20or%20heading.). 

It is also not recommended to [mention package names](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#The-DESCRIPTION-file) in the Title.
:::
