---
title: "Welcome to the CRAN Cookbook"
subtitle: "A complementary self-service guide to discover solutions to common CRAN submission issues"
---


# Introduction

The CRAN Cookbook has been developed as part of a special project grant from the R Consortium in 2024. The proposal is titled: **Improving the Skills of R Package Maintainers**. The goals of the project are:

1. Educate a diverse cohort of young R developers to acquire the technical knowledge and skills required to participate in the continuous integration of R packages into the R ecosystem.
2. Develop a new documentation solution with a Quarto website that is user-friendly for new R package maintainers on CRAN.
3. Identify common CRAN submission issues and create a framework of "problems" and "solutions" that are easy to implement and discover.


# Prerequisites

1. **Beginner to intermediate knowledge of R Programming**: This guide is designed to assist both first-time R package maintainers and those with experience who prefer to navigate a curated selection of the most common issues encountered when submitting to CRAN, as identified by CRAN Maintainers. It provides a 'best practices' approach to resolving R package issues to facilitate a successful re-submission to CRAN.

2. **Experience in debugging code**: Submitting your R package to CRAN is a multi-step process that may involve communicating with multiple CRAN volunteers and updating your code, tests, examples, documentation, and other supplementary files to meet acceptance criteria. Developing strong debugging skills can be particularly valuable during this process, as it can help you effectively apply the examples in this cookbook to create custom solutions for updating your R package.


# Additional Resources

- [Writing R Extensions](https://cran.r-project.org/doc/manuals/R-exts.html)

- [CRAN Repository Policy](https://cran.r-project.org/web/packages/policies.html)

- [Checklist for CRAN submissions](https://cran.r-project.org/web/packages/submission_checklist.html)

- ["R Packages" by Hadley Wickham and Jennifer Bryan](https://r-pkgs.org/)
